wifi:
  on_connect:
    - light.turn_on:
        id: rgb_light
        brightness: 100%
        red: 0
        green: 0
        blue: 100%
    - delay: 5s
    - light.turn_off:
        id: rgb_light
  on_disconnect:
    - light.turn_on:
        id: rgb_light
        brightness: 100%
        red: 100%
        green: 0
        blue: 0
