wifi:
  ap:
    ssid: "${device}-${room} FH"
    password: !secret wifi_ap_password
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
    - ssid: !secret wifi_ssid_3
      password: !secret wifi_password_3
api:
  encryption:
    key: !secret encryption_key
esphome:
  name: ${identity}-${device}-${room}
  name_add_mac_suffix: false
  friendly_name: ${room} ${device}
