wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.40.${identity}
    gateway: !secret gateway
    subnet: !secret subnet
api:
  encryption:
    key: !secret encryption_key
esphome:
  name: ${identity}-${device}-${room}
  name_add_mac_suffix: false
  friendly_name: ${room} ${device}