packages:
  ApolloAutomation.MSR-1: github://ApolloAutomation/MSR-1/Integrations/ESPHome/MSR-1_Factory.yaml
  common: !include
    file: ./common/settings.yaml
    vars:
      device: apollo
      room: office
      identity: 10
  extra: !include ./common/apollo-extra.yaml
substitutions:
  name: apollo-office