packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-no-ble.yaml@main
  common: !include
    file: ./common/settings.yaml
    vars:
      device: epl1
      room: living-room
      identity: 13
  extra: !include ./common/epl-extra.yaml
    